version: '2'

services:
  mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    volumes:
      - /data/db
   # command: mongod
  mysql:
      image: mysql:latest
      ports:
        - "3307:3306"
      volumes:
        - /var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: test123
        MYSQL_DATABASE: myweather
        MYSQL_USER: test
        MYSQL_PASSWORD: test123
#  web:
#    image: java:openjdk-8u91-jdk
#    working_dir: /app
#    volumes:
#      - ./myweather:/app
#    command: java -jar /app/myweather-0.0.1-SNAPSHOT.jar
#    ports:
#      - "8080:8080"
#    links:
#      - mongodb
#    environment:
#      - SPRING_DATA_MONGODB_URI:mongodb://mongodb/myweather
